# clrsync template

[colors.primary]
background = '{background}'
foreground = '{foreground}'

[colors.cursor]
text = '{background}'
cursor = '{cursor}'

[colors.vi_mode_cursor]
text = '{background}'
cursor = '{cursor}'

[colors.selection]
text = 'CellForeground'
background = '{editor_selection}'

[colors.search.matches]
foreground = '{on_accent}'
background = '{editor_search_match_active}'

[colors.search.focused_match]
foreground = '{on_accent}'
background = '{accent}'

[colors.footer_bar]
foreground = '{foreground}'
background = '{surface}'

[colors.hints.start]
foreground = '{on_warning}'
background = '{warning}'

[colors.hints.end]
foreground = '{on_surface}'
background = '{surface_variant}'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.normal]
black   = '{term0}'
red     = '{term1}'
green   = '{term2}'
yellow  = '{term3}'
blue    = '{term4}'
magenta = '{term5}'
cyan    = '{term6}'
white   = '{term7}'

[colors.bright]
black   = '{term8}'
red     = '{term9}'
green   = '{term10}'
yellow  = '{term11}'
blue    = '{term12}'
magenta = '{term13}'
cyan    = '{term14}'
white   = '{term15}'
