$primary = rgb({accent.hex_stripped})
$surface = rgb({surface.hex_stripped})
$secondary = rgb({base04.hex_stripped})
$error = rgb({error.hex_stripped})
$tertiary = rgb({base06.hex_stripped})
$surface_lowest = rgb({background.hex_stripped})

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}